# Notebook to Sample from Data Set

In [10]:
# At random, need distribution of season, time but not equal

import pandas as pd
import numpy as np
import random

# Read Files
busses = pd.read_excel('Busses_Timeseries_Table_Set2022_ExcelEdit.xlsx')
edges = pd.read_excel('Edges_Timeseries_Table_Set2022_ExcelEdit.xlsx')

In [11]:
timestamps = edges['datetime_beginning_utc'].unique()
times = timestamps.size

sampleSize = 1000
sample = random.sample(list(timestamps), sampleSize)

bussesSample = busses.loc[busses['datetime_beginning_utc'].isin(sample)]
bussesSample = bussesSample.sort_values(by=['datetime_beginning_utc', 'bus_id'], ascending=True)

edgesSample = edges.loc[edges['datetime_beginning_utc'].isin(sample)]
edgesSample = edgesSample.sort_values(by=['datetime_beginning_utc', 'From Number', 'To Number'], ascending=True)

In [12]:
bussesSample

,datetime_beginning_utc,bus_id,load_area,mw_norm,solTheta,min_ecomin,max_ecomax,inter_start_cost,incremental_price,solGenerate,solOn
56,2019-06-01 06:00:00,0,AECO,2.40,4358.297677,81.0,202.5,20427.25,21.505539,202.5,1
57,2019-06-01 06:00:00,1,AEPAPT,9.43,2213.643718,25.0,46.9,52.50,44.678852,46.9,1
58,2019-06-01 06:00:00,2,AEPIMP,6.93,3893.513189,0.0,0.0,0.00,0.000000,0.0,0
59,2019-06-01 06:00:00,3,AEPKPT,1.43,2050.442018,0.0,0.0,0.00,0.000000,0.0,0
60,2019-06-01 06:00:00,4,AEPOPT,14.49,2187.353552,25.0,46.9,52.50,44.678852,46.9,1
...,...,...,...,...,...,...,...,...,...,...,...
244995,2020-05-31 17:00:00,23,PN,3.63,854.880270,0.0,0.0,0.00,0.000000,0.0,0
244996,2020-05-31 17:00:00,24,PS,11.06,589.204745,0.0,0.0,0.00,0.000000,0.0,0
244997,2020-05-31 17:00:00,25,RECO,0.47,587.967903,0.0,0.0,0.00,0.000000,0.0,0
244998,2020-05-31 17:00:00,26,SMECO,185.64,332.954647,0.0,0.0,0.00,0.000000,0.0,0
244999,2020-05-31 17:00:00,27,UGI,0.25,502.423728,0.0,0.0,0.00,0.000000,0.0,0

In [13]:
bussesSample.to_csv("Busses_Timeseries_Table_Set2022_Sample.csv")
edgesSample.to_csv("Edges_Timeseries_Table_Set2022_Sample.csv")